### ISSUE TITLE
pytest filterwarnings translated incorrectly

### ISSUE THREAD

**Issue by graingert** [abravalheri/ini2toml#74]
input:

```ini
[pytest]
filterwarnings=
    error
    ignore:Please use `dok_matrix` from the `scipy\.sparse` namespace, the `scipy\.sparse\.dok` namespace is deprecated.:DeprecationWarning
```

output:

```toml
[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore:Please", "use", "`dok_matrix`", "from", "the", '`scipy\.sparse`', "namespace,", "the", '`scipy\.sparse\.dok`', "namespace", "is", "deprecated.:DeprecationWarning",
]

[tool.setuptools]
include-package-data = false
```

expected:

```
[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    """ignore:Please use `dok_matrix` from the `scipy\.sparse` namespace, the `scipy\.sparse\.dok` namespace is deprecated.:DeprecationWarning""",
]

[tool.setuptools]
include-package-data = false
```
