### ISSUE TITLE
keywords not translated as expected

### ISSUE THREAD

**Issue by jaraco** [abravalheri/ini2toml#92]
```shell
 draft @ cat setup.cfg
[options]
keywords = foo bar baz
 draft @ pip-run 'ini2toml[lite]' -- -m ini2toml setup.cfg
```
```toml
[build-system]
requires = [
    "setuptools>=61.2",
]
build-backend = "setuptools.build_meta"

[project]
dynamic = [
    "version",
]

[tool.setuptools]
keywords = "foo bar baz"
include-package-data = false
```

So that's mostly good, but `tool.setuptools.keywords` is incorrect and attempting to use it will result in an error. Instead, I think the right syntax is:

```toml
[project]
keywords = [
  "foo",
  "bar",
  "baz",
]
```
